/* tslint:disable */
/* eslint-disable */
/**
 * Project management tool API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateProjectDto
 */
export interface UpdateProjectDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDto
     */
    'colour'?: UpdateProjectDtoColourEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateProjectDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateProjectDto
     */
    'name': string;
}

export const UpdateProjectDtoColourEnum = {
    B8255f: '#b8255f',
    Cf473a: '#cf473a',
    C77100: '#c77100',
    B29104: '#b29104',
    _949c31: '#949c31',
    _65a33a: '#65a33a',
    _369307: '#369307',
    _42a393: '#42a393',
    _148fad: '#148fad',
    _319dc0: '#319dc0',
    _6988a4: '#6988a4',
    _2a67e2: '#2a67e2',
    _692ec2: '#692ec2',
    Ac30cc: '#ac30cc',
    A4698c: '#a4698c',
    E05095: '#e05095',
    B2635c: '#b2635c',
    _808080: '#808080',
    _999999: '#999999',
    _8f7a69: '#8f7a69'
} as const;

export type UpdateProjectDtoColourEnum = typeof UpdateProjectDtoColourEnum[keyof typeof UpdateProjectDtoColourEnum];


