/* tslint:disable */
/* eslint-disable */
/**
 * Project management tool API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateTaskDto
 */
export interface UpdateTaskDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateTaskDto
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'description': string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskDto
     */
    'dueDate': string | null;
    /**
     * 
     * @type {object}
     * @memberof UpdateTaskDto
     */
    'priority': object | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTaskDto
     */
    'projectId': number | null;
}

